package org.bytedeco.opencascade.frameworks.foundation;

import org.bytedeco.javacpp.Loader;
import org.bytedeco.javacpp.annotation.Platform;
import org.bytedeco.javacpp.annotation.Properties;
import org.bytedeco.javacpp.tools.Info;
import org.bytedeco.javacpp.tools.InfoMap;
import org.bytedeco.javacpp.tools.InfoMapper;

/**
 *
 * @author Michael Maenz
 */
@Properties(value = { @Platform(link = "opencascade", include = { "opencascade/NCollection_DefineAlloc.hxx",
        "opencascade/NCollection_DefineArray1.hxx", "opencascade/NCollection_DefineArray2.hxx",
        "opencascade/NCollection_DefineDataMap.hxx", "opencascade/NCollection_DefineDoubleMap.hxx",
        "opencascade/NCollection_DefineHArray1.hxx", "opencascade/NCollection_DefineHArray2.hxx",
        "opencascade/NCollection_DefineHSequence.hxx", "opencascade/NCollection_DefineIndexedDataMap.hxx",
        "opencascade/NCollection_DefineIndexedMap.hxx", "opencascade/NCollection_DefineList.hxx",
        "opencascade/NCollection_DefineMap.hxx", "opencascade/NCollection_DefineSequence.hxx",
        "opencascade/Standard_DefineAlloc.hxx", "opencascade/Standard_DefineException.hxx",
        "opencascade/Standard_DefineHandle.hxx", "opencascade/NCollection_DefineVector.hxx", "opencascade/BSplCLib.hxx",
        "opencascade/BSplCLib.lxx", "opencascade/BSplCLib_Cache.hxx", "opencascade/BSplCLib_CacheParams.hxx",
        "opencascade/BSplCLib_CurveComputation.gxx", "opencascade/BSplCLib_EvaluatorFunction.hxx",
        "opencascade/BSplCLib_KnotDistribution.hxx", "opencascade/BSplCLib_MultDistribution.hxx",
        "opencascade/BSplSLib.hxx", "opencascade/BSplSLib.lxx", "opencascade/BSplSLib_Cache.hxx",
        "opencascade/BSplSLib_EvaluatorFunction.hxx", "opencascade/BVH_BinaryTree.hxx",
        "opencascade/BVH_BinnedBuilder.hxx", "opencascade/BVH_Box.hxx", "opencascade/BVH_BoxSet.hxx",
        "opencascade/BVH_BuildQueue.hxx", "opencascade/BVH_BuildThread.hxx", "opencascade/BVH_Builder.hxx",
        "opencascade/BVH_Constants.hxx", "opencascade/BVH_Distance.hxx", "opencascade/BVH_DistanceField.hxx",
        "opencascade/BVH_DistanceField.lxx", "opencascade/BVH_Geometry.hxx", "opencascade/BVH_IndexedBoxSet.hxx",
        "opencascade/BVH_LinearBuilder.hxx", "opencascade/BVH_Object.hxx", "opencascade/BVH_ObjectSet.hxx",
        "opencascade/BVH_PairDistance.hxx", "opencascade/BVH_PrimitiveSet.hxx", "opencascade/BVH_PrimitiveSet3d.hxx",
        "opencascade/BVH_Properties.hxx", "opencascade/BVH_QuadTree.hxx", "opencascade/BVH_QueueBuilder.hxx",
        "opencascade/BVH_QuickSorter.hxx", "opencascade/BVH_RadixSorter.hxx", "opencascade/BVH_Set.hxx",
        "opencascade/BVH_Sorter.hxx", "opencascade/BVH_SpatialMedianBuilder.hxx",
        "opencascade/BVH_SweepPlaneBuilder.hxx", "opencascade/BVH_Tools.hxx", "opencascade/BVH_Traverse.hxx",
        "opencascade/BVH_Traverse.lxx", "opencascade/BVH_Tree.hxx", "opencascade/BVH_Triangulation.hxx",
        "opencascade/BVH_Types.hxx", "opencascade/Bnd_Array1OfBox.hxx", "opencascade/Bnd_Array1OfBox2d.hxx",
        "opencascade/Bnd_Array1OfSphere.hxx", "opencascade/Bnd_B2d.hxx", "opencascade/Bnd_B2f.hxx",
        "opencascade/Bnd_B2x.gxx", "opencascade/Bnd_B2x.lxx", "opencascade/Bnd_B3d.hxx", "opencascade/Bnd_B3f.hxx",
        "opencascade/Bnd_B3x.gxx", "opencascade/Bnd_B3x.lxx", "opencascade/Bnd_BoundSortBox.hxx",
        "opencascade/Bnd_BoundSortBox2d.hxx", "opencascade/Bnd_Box.hxx", "opencascade/Bnd_Box2d.hxx",
        "opencascade/Bnd_HArray1OfBox.hxx", "opencascade/Bnd_HArray1OfBox2d.hxx", "opencascade/Bnd_HArray1OfSphere.hxx",
        "opencascade/Bnd_OBB.hxx", "opencascade/Bnd_Range.hxx", "opencascade/Bnd_SeqOfBox.hxx",
        "opencascade/Bnd_Sphere.hxx", "opencascade/Bnd_Sphere.lxx", "opencascade/Bnd_Tools.hxx",
        "opencascade/CSLib.hxx", "opencascade/CSLib_Class2d.hxx", "opencascade/CSLib_DerivativeStatus.hxx",
        "opencascade/CSLib_NormalPolyDef.hxx", "opencascade/CSLib_NormalStatus.hxx",
        "opencascade/Convert_CircleToBSplineCurve.hxx", "opencascade/Convert_CompBezierCurves2dToBSplineCurve2d.hxx",
        "opencascade/Convert_CompBezierCurvesToBSplineCurve.hxx", "opencascade/Convert_CompPolynomialToPoles.hxx",
        "opencascade/Convert_ConeToBSplineSurface.hxx", "opencascade/Convert_ConicToBSplineCurve.hxx",
        "opencascade/Convert_CosAndSinEvalFunction.hxx", "opencascade/Convert_CylinderToBSplineSurface.hxx",
        "opencascade/Convert_ElementarySurfaceToBSplineSurface.hxx", "opencascade/Convert_EllipseToBSplineCurve.hxx",
        "opencascade/Convert_GridPolynomialToPoles.hxx", "opencascade/Convert_HyperbolaToBSplineCurve.hxx",
        "opencascade/Convert_ParabolaToBSplineCurve.hxx", "opencascade/Convert_ParameterisationType.hxx",
        "opencascade/Convert_PolynomialCosAndSin.hxx", "opencascade/Convert_SequenceOfArray1OfPoles.hxx",
        "opencascade/Convert_SequenceOfArray1OfPoles2d.hxx", "opencascade/Convert_SphereToBSplineSurface.hxx",
        "opencascade/Convert_TorusToBSplineSurface.hxx", "opencascade/ElCLib.hxx", "opencascade/ElCLib.lxx",
        "opencascade/ElSLib.hxx", "opencascade/ElSLib.lxx", "opencascade/Expr.hxx", "opencascade/ExprIntrp.hxx",
        "opencascade/ExprIntrp.tab.h", "opencascade/ExprIntrp_Analysis.hxx", "opencascade/ExprIntrp_GenExp.hxx",
        "opencascade/ExprIntrp_GenFct.hxx", "opencascade/ExprIntrp_GenRel.hxx", "opencascade/ExprIntrp_Generator.hxx",
        "opencascade/ExprIntrp_ListIteratorOfStackOfGeneralExpression.hxx",
        "opencascade/ExprIntrp_ListIteratorOfStackOfGeneralFunction.hxx",
        "opencascade/ExprIntrp_ListIteratorOfStackOfGeneralRelation.hxx",
        "opencascade/ExprIntrp_SequenceOfNamedExpression.hxx", "opencascade/ExprIntrp_SequenceOfNamedFunction.hxx",
        "opencascade/ExprIntrp_StackOfGeneralExpression.hxx", "opencascade/ExprIntrp_StackOfGeneralFunction.hxx",
        "opencascade/ExprIntrp_StackOfGeneralRelation.hxx", "opencascade/ExprIntrp_SyntaxError.hxx",
        "opencascade/ExprIntrp_yaccanal.hxx", "opencascade/ExprIntrp_yaccintrf.hxx", "opencascade/Expr_Absolute.hxx",
        "opencascade/Expr_ArcCosine.hxx", "opencascade/Expr_ArcSine.hxx", "opencascade/Expr_ArcTangent.hxx",
        "opencascade/Expr_ArgCosh.hxx", "opencascade/Expr_ArgSinh.hxx", "opencascade/Expr_ArgTanh.hxx",
        "opencascade/Expr_Array1OfGeneralExpression.hxx", "opencascade/Expr_Array1OfNamedUnknown.hxx",
        "opencascade/Expr_Array1OfSingleRelation.hxx", "opencascade/Expr_BinaryExpression.hxx",
        "opencascade/Expr_BinaryExpression.lxx", "opencascade/Expr_BinaryFunction.hxx", "opencascade/Expr_Cosh.hxx",
        "opencascade/Expr_Cosine.hxx", "opencascade/Expr_Difference.hxx", "opencascade/Expr_Different.hxx",
        "opencascade/Expr_Division.hxx", "opencascade/Expr_Equal.hxx", "opencascade/Expr_Exponential.hxx",
        "opencascade/Expr_Exponentiate.hxx", "opencascade/Expr_ExprFailure.hxx",
        "opencascade/Expr_FunctionDerivative.hxx", "opencascade/Expr_GeneralExpression.hxx",
        "opencascade/Expr_GeneralFunction.hxx", "opencascade/Expr_GeneralRelation.hxx",
        "opencascade/Expr_GreaterThan.hxx", "opencascade/Expr_GreaterThanOrEqual.hxx",
        "opencascade/Expr_InvalidAssignment.hxx", "opencascade/Expr_InvalidFunction.hxx",
        "opencascade/Expr_InvalidOperand.hxx", "opencascade/Expr_LessThan.hxx", "opencascade/Expr_LessThanOrEqual.hxx",
        "opencascade/Expr_LogOf10.hxx", "opencascade/Expr_LogOfe.hxx", "opencascade/Expr_MapOfNamedUnknown.hxx",
        "opencascade/Expr_NamedConstant.hxx", "opencascade/Expr_NamedConstant.lxx",
        "opencascade/Expr_NamedExpression.hxx", "opencascade/Expr_NamedFunction.hxx",
        "opencascade/Expr_NamedUnknown.hxx", "opencascade/Expr_NamedUnknown.lxx", "opencascade/Expr_NotAssigned.hxx",
        "opencascade/Expr_NotEvaluable.hxx", "opencascade/Expr_NumericValue.hxx", "opencascade/Expr_Operators.hxx",
        "opencascade/Expr_PolyExpression.hxx", "opencascade/Expr_PolyExpression.lxx",
        "opencascade/Expr_PolyFunction.hxx", "opencascade/Expr_Product.hxx", "opencascade/Expr_RUIterator.hxx",
        "opencascade/Expr_RelationIterator.hxx", "opencascade/Expr_SequenceOfGeneralExpression.hxx",
        "opencascade/Expr_SequenceOfGeneralRelation.hxx", "opencascade/Expr_Sign.hxx", "opencascade/Expr_Sine.hxx",
        "opencascade/Expr_SingleRelation.hxx", "opencascade/Expr_Sinh.hxx", "opencascade/Expr_Square.hxx",
        "opencascade/Expr_SquareRoot.hxx", "opencascade/Expr_Sum.hxx", "opencascade/Expr_SystemRelation.hxx",
        "opencascade/Expr_Tangent.hxx", "opencascade/Expr_Tanh.hxx", "opencascade/Expr_UnaryExpression.hxx",
        "opencascade/Expr_UnaryExpression.lxx", "opencascade/Expr_UnaryFunction.hxx", "opencascade/Expr_UnaryMinus.hxx",
        "opencascade/Expr_UnknownIterator.hxx", "opencascade/FSD_BStream.hxx", "opencascade/FSD_Base64Decoder.hxx",
        "opencascade/FSD_BinaryFile.hxx", "opencascade/FSD_CmpFile.hxx", "opencascade/FSD_FStream.hxx",
        "opencascade/FSD_File.hxx", "opencascade/FSD_FileHeader.hxx", "opencascade/GeomAbs_BSplKnotDistribution.hxx",
        "opencascade/GeomAbs_CurveForm.hxx", "opencascade/GeomAbs_CurveType.hxx", "opencascade/GeomAbs_IsoType.hxx",
        "opencascade/GeomAbs_JoinType.hxx", "opencascade/GeomAbs_Shape.hxx", "opencascade/GeomAbs_SurfaceForm.hxx",
        "opencascade/GeomAbs_SurfaceType.hxx", "opencascade/GeomAbs_UVSense.hxx", "opencascade/MMgt_TShared.hxx",
        "opencascade/Message.hxx", "opencascade/Message_Alert.hxx", "opencascade/Message_Algorithm.hxx",
        "opencascade/Message_Algorithm.lxx", "opencascade/Message_ExecStatus.hxx", "opencascade/Message_Gravity.hxx",
        "opencascade/Message_HArrayOfMsg.hxx", "opencascade/Message_ListIteratorOfListOfMsg.hxx",
        "opencascade/Message_ListOfAlert.hxx", "opencascade/Message_ListOfMsg.hxx", "opencascade/Message_Messenger.hxx",
        "opencascade/Message_Msg.hxx", "opencascade/Message_Msg.lxx", "opencascade/Message_MsgFile.hxx",
        "opencascade/Message_Printer.hxx", "opencascade/Message_PrinterOStream.hxx",
        "opencascade/Message_ProgressIndicator.hxx", "opencascade/Message_ProgressIndicator.lxx",
        "opencascade/Message_ProgressScale.hxx", "opencascade/Message_ProgressScale.lxx",
        "opencascade/Message_ProgressSentry.hxx", "opencascade/Message_ProgressSentry.lxx",
        "opencascade/Message_Report.hxx", "opencascade/Message_SequenceOfPrinters.hxx",
        "opencascade/Message_SequenceOfProgressScale.hxx", "opencascade/Message_Status.hxx",
        "opencascade/Message_StatusType.hxx", "opencascade/NCollection_AccAllocator.hxx",
        "opencascade/NCollection_AlignedAllocator.hxx", "opencascade/NCollection_Array1.hxx",
        "opencascade/NCollection_Array2.hxx", "opencascade/NCollection_BaseAllocator.hxx",
        "opencascade/NCollection_BaseList.hxx", "opencascade/NCollection_BaseMap.hxx",
        "opencascade/NCollection_BaseSequence.hxx", "opencascade/NCollection_BaseVector.hxx",
        "opencascade/NCollection_Buffer.hxx", "opencascade/NCollection_CellFilter.hxx",
        "opencascade/NCollection_Comparator.hxx", "opencascade/NCollection_DataMap.hxx",
        "opencascade/NCollection_DefaultHasher.hxx", "opencascade/NCollection_DoubleMap.hxx",
        "opencascade/NCollection_EBTree.hxx", "opencascade/NCollection_HArray1.hxx",
        "opencascade/NCollection_HArray2.hxx", "opencascade/NCollection_HSequence.hxx",
        "opencascade/NCollection_Haft.h", "opencascade/NCollection_Handle.hxx",
        "opencascade/NCollection_HeapAllocator.hxx", "opencascade/NCollection_IncAllocator.hxx",
        "opencascade/NCollection_IndexedDataMap.hxx", "opencascade/NCollection_IndexedMap.hxx",
        "opencascade/NCollection_Lerp.hxx", "opencascade/NCollection_List.hxx", "opencascade/NCollection_ListNode.hxx",
        "opencascade/NCollection_LocalArray.hxx", "opencascade/NCollection_Map.hxx", "opencascade/NCollection_Mat4.hxx",
        "opencascade/NCollection_Sequence.hxx", "opencascade/NCollection_Shared.hxx",
        "opencascade/NCollection_SparseArray.hxx", "opencascade/NCollection_SparseArrayBase.hxx",
        "opencascade/NCollection_StdAllocator.hxx", "opencascade/NCollection_StlIterator.hxx",
        "opencascade/NCollection_String.hxx", "opencascade/NCollection_TListIterator.hxx",
        "opencascade/NCollection_TListNode.hxx", "opencascade/NCollection_TypeDef.hxx",
        "opencascade/NCollection_UBTree.hxx", "opencascade/NCollection_UBTreeFiller.hxx",
        "opencascade/NCollection_UtfIterator.hxx", "opencascade/NCollection_UtfIterator.lxx",
        "opencascade/NCollection_UtfString.hxx", "opencascade/NCollection_UtfString.lxx",
        "opencascade/NCollection_Vec2.hxx", "opencascade/NCollection_Vec3.hxx", "opencascade/NCollection_Vec4.hxx",
        "opencascade/NCollection_Vector.hxx", "opencascade/NCollection_WinHeapAllocator.hxx", "opencascade/OSD.hxx",
        "opencascade/OSD_Chronometer.hxx", "opencascade/OSD_Directory.hxx", "opencascade/OSD_DirectoryIterator.hxx",
        "opencascade/OSD_Disk.hxx", "opencascade/OSD_Environment.hxx", "opencascade/OSD_Error.hxx",
        "opencascade/OSD_ErrorList.hxx", "opencascade/OSD_Exception.hxx",
        "opencascade/OSD_Exception_ACCESS_VIOLATION.hxx", "opencascade/OSD_Exception_ARRAY_BOUNDS_EXCEEDED.hxx",
        "opencascade/OSD_Exception_CTRL_BREAK.hxx", "opencascade/OSD_Exception_FLT_DENORMAL_OPERAND.hxx",
        "opencascade/OSD_Exception_FLT_DIVIDE_BY_ZERO.hxx", "opencascade/OSD_Exception_FLT_INEXACT_RESULT.hxx",
        "opencascade/OSD_Exception_FLT_INVALID_OPERATION.hxx", "opencascade/OSD_Exception_FLT_OVERFLOW.hxx",
        "opencascade/OSD_Exception_FLT_STACK_CHECK.hxx", "opencascade/OSD_Exception_FLT_UNDERFLOW.hxx",
        "opencascade/OSD_Exception_ILLEGAL_INSTRUCTION.hxx", "opencascade/OSD_Exception_INT_DIVIDE_BY_ZERO.hxx",
        "opencascade/OSD_Exception_INT_OVERFLOW.hxx", "opencascade/OSD_Exception_INVALID_DISPOSITION.hxx",
        "opencascade/OSD_Exception_IN_PAGE_ERROR.hxx", "opencascade/OSD_Exception_NONCONTINUABLE_EXCEPTION.hxx",
        "opencascade/OSD_Exception_PRIV_INSTRUCTION.hxx", "opencascade/OSD_Exception_STACK_OVERFLOW.hxx",
        "opencascade/OSD_Exception_STATUS_NO_MEMORY.hxx", "opencascade/OSD_File.hxx",
        "opencascade/OSD_FileIterator.hxx", "opencascade/OSD_FileNode.hxx", "opencascade/OSD_FromWhere.hxx",
        "opencascade/OSD_Function.hxx", "opencascade/OSD_Host.hxx", "opencascade/OSD_KindFile.hxx",
        "opencascade/OSD_LoadMode.hxx", "opencascade/OSD_LockType.hxx", "opencascade/OSD_MAllocHook.hxx",
        "opencascade/OSD_MemInfo.hxx", "opencascade/OSD_OEMType.hxx", "opencascade/OSD_OSDError.hxx",
        "opencascade/OSD_OpenFile.hxx", "opencascade/OSD_OpenMode.hxx", "opencascade/OSD_PThread.hxx",
        "opencascade/OSD_Parallel.hxx", "opencascade/OSD_Path.hxx", "opencascade/OSD_PerfMeter.h",
        "opencascade/OSD_PerfMeter.hxx", "opencascade/OSD_Process.hxx", "opencascade/OSD_Protection.hxx",
        "opencascade/OSD_SIGBUS.hxx", "opencascade/OSD_SIGHUP.hxx", "opencascade/OSD_SIGILL.hxx",
        "opencascade/OSD_SIGINT.hxx", "opencascade/OSD_SIGKILL.hxx", "opencascade/OSD_SIGQUIT.hxx",
        "opencascade/OSD_SIGSEGV.hxx", "opencascade/OSD_SIGSYS.hxx", "opencascade/OSD_SharedLibrary.hxx",
        "opencascade/OSD_Signal.hxx", "opencascade/OSD_SignalMode.hxx", "opencascade/OSD_SingleProtection.hxx",
        "opencascade/OSD_SysType.hxx", "opencascade/OSD_Thread.hxx", "opencascade/OSD_ThreadFunction.hxx",
        "opencascade/OSD_ThreadPool.hxx", "opencascade/OSD_Timer.hxx", "opencascade/OSD_WNT.hxx",
        "opencascade/OSD_WhoAmI.hxx", "opencascade/PLib.hxx", "opencascade/PLib_Base.hxx",
        "opencascade/PLib_DoubleJacobiPolynomial.hxx", "opencascade/PLib_DoubleJacobiPolynomial.lxx",
        "opencascade/PLib_HermitJacobi.hxx", "opencascade/PLib_HermitJacobi.lxx",
        "opencascade/PLib_JacobiPolynomial.hxx", "opencascade/PLib_JacobiPolynomial.lxx", "opencascade/Plugin.hxx",
        "opencascade/Plugin_DataMapIteratorOfMapOfFunctions.hxx", "opencascade/Plugin_Failure.hxx",
        "opencascade/Plugin_Macro.hxx", "opencascade/Plugin_MapOfFunctions.hxx", "opencascade/Poly.hxx",
        "opencascade/Poly_Array1OfTriangle.hxx", "opencascade/Poly_CoherentLink.hxx",
        "opencascade/Poly_CoherentNode.hxx", "opencascade/Poly_CoherentTriPtr.hxx",
        "opencascade/Poly_CoherentTriangle.hxx", "opencascade/Poly_CoherentTriangulation.hxx",
        "opencascade/Poly_Connect.hxx", "opencascade/Poly_HArray1OfTriangle.hxx",
        "opencascade/Poly_ListOfTriangulation.hxx", "opencascade/Poly_MakeLoops.hxx", "opencascade/Poly_Polygon2D.hxx",
        "opencascade/Poly_Polygon2D.lxx", "opencascade/Poly_Polygon3D.hxx", "opencascade/Poly_Polygon3D.lxx",
        "opencascade/Poly_PolygonOnTriangulation.hxx", "opencascade/Poly_PolygonOnTriangulation.lxx",
        "opencascade/Poly_Triangle.hxx", "opencascade/Poly_Triangle.lxx", "opencascade/Poly_Triangulation.hxx",
        "opencascade/Precision.hxx", "opencascade/Quantity_AbsorbedDose.hxx", "opencascade/Quantity_Acceleration.hxx",
        "opencascade/Quantity_AcousticIntensity.hxx", "opencascade/Quantity_Activity.hxx",
        "opencascade/Quantity_Admittance.hxx", "opencascade/Quantity_AmountOfSubstance.hxx",
        "opencascade/Quantity_AngularVelocity.hxx", "opencascade/Quantity_Area.hxx",
        "opencascade/Quantity_Array1OfColor.hxx", "opencascade/Quantity_Array2OfColor.hxx",
        "opencascade/Quantity_Capacitance.hxx", "opencascade/Quantity_Coefficient.hxx",
        "opencascade/Quantity_CoefficientOfExpansion.hxx", "opencascade/Quantity_Color.hxx",
        "opencascade/Quantity_ColorDefinitionError.hxx", "opencascade/Quantity_ColorHasher.hxx",
        "opencascade/Quantity_ColorRGBA.hxx", "opencascade/Quantity_ColorRGBAHasher.hxx",
        "opencascade/Quantity_Concentration.hxx", "opencascade/Quantity_Conductivity.hxx",
        "opencascade/Quantity_Constant.hxx", "opencascade/Quantity_Consumption.hxx", "opencascade/Quantity_Content.hxx",
        "opencascade/Quantity_Date.hxx", "opencascade/Quantity_DateDefinitionError.hxx",
        "opencascade/Quantity_Density.hxx", "opencascade/Quantity_DoseEquivalent.hxx",
        "opencascade/Quantity_ElectricCapacitance.hxx", "opencascade/Quantity_ElectricCharge.hxx",
        "opencascade/Quantity_ElectricCurrent.hxx", "opencascade/Quantity_ElectricFieldStrength.hxx",
        "opencascade/Quantity_ElectricPotential.hxx", "opencascade/Quantity_Energy.hxx",
        "opencascade/Quantity_Enthalpy.hxx", "opencascade/Quantity_Entropy.hxx", "opencascade/Quantity_Factor.hxx",
        "opencascade/Quantity_Force.hxx", "opencascade/Quantity_Frequency.hxx",
        "opencascade/Quantity_HArray1OfColor.hxx", "opencascade/Quantity_Illuminance.hxx",
        "opencascade/Quantity_Impedance.hxx", "opencascade/Quantity_Index.hxx", "opencascade/Quantity_Inductance.hxx",
        "opencascade/Quantity_KinematicViscosity.hxx", "opencascade/Quantity_KineticMoment.hxx",
        "opencascade/Quantity_Length.hxx", "opencascade/Quantity_Luminance.hxx",
        "opencascade/Quantity_LuminousEfficacity.hxx", "opencascade/Quantity_LuminousExposition.hxx",
        "opencascade/Quantity_LuminousFlux.hxx", "opencascade/Quantity_LuminousIntensity.hxx",
        "opencascade/Quantity_MagneticFieldStrength.hxx", "opencascade/Quantity_MagneticFlux.hxx",
        "opencascade/Quantity_MagneticFluxDensity.hxx", "opencascade/Quantity_Mass.hxx",
        "opencascade/Quantity_MassFlow.hxx", "opencascade/Quantity_MolarConcentration.hxx",
        "opencascade/Quantity_MolarMass.hxx", "opencascade/Quantity_MolarVolume.hxx",
        "opencascade/Quantity_Molarity.hxx", "opencascade/Quantity_MomentOfAForce.hxx",
        "opencascade/Quantity_MomentOfInertia.hxx", "opencascade/Quantity_Momentum.hxx",
        "opencascade/Quantity_NameOfColor.hxx", "opencascade/Quantity_Normality.hxx",
        "opencascade/Quantity_Parameter.hxx", "opencascade/Quantity_Period.hxx",
        "opencascade/Quantity_PeriodDefinitionError.hxx", "opencascade/Quantity_PhysicalQuantity.hxx",
        "opencascade/Quantity_PlaneAngle.hxx", "opencascade/Quantity_Power.hxx", "opencascade/Quantity_Pressure.hxx",
        "opencascade/Quantity_Quotient.hxx", "opencascade/Quantity_Rate.hxx", "opencascade/Quantity_Ratio.hxx",
        "opencascade/Quantity_Reluctance.hxx", "opencascade/Quantity_Resistance.hxx",
        "opencascade/Quantity_Resistivity.hxx", "opencascade/Quantity_Scalaire.hxx",
        "opencascade/Quantity_SolidAngle.hxx", "opencascade/Quantity_SoundIntensity.hxx",
        "opencascade/Quantity_SpecificHeatCapacity.hxx", "opencascade/Quantity_Speed.hxx",
        "opencascade/Quantity_SurfaceTension.hxx", "opencascade/Quantity_Temperature.hxx",
        "opencascade/Quantity_ThermalConductivity.hxx", "opencascade/Quantity_Torque.hxx",
        "opencascade/Quantity_TypeOfColor.hxx", "opencascade/Quantity_Velocity.hxx",
        "opencascade/Quantity_Viscosity.hxx", "opencascade/Quantity_Volume.hxx", "opencascade/Quantity_VolumeFlow.hxx",
        "opencascade/Quantity_Weight.hxx", "opencascade/Quantity_Work.hxx", "opencascade/Resource_Big5.h",
        "opencascade/Resource_ConvertUnicode.hxx",
        "opencascade/Resource_DataMapIteratorOfDataMapOfAsciiStringAsciiString.hxx",
        "opencascade/Resource_DataMapIteratorOfDataMapOfAsciiStringExtendedString.hxx",
        "opencascade/Resource_DataMapOfAsciiStringAsciiString.hxx",
        "opencascade/Resource_DataMapOfAsciiStringExtendedString.hxx", "opencascade/Resource_FormatType.hxx",
        "opencascade/Resource_GB2312.h", "opencascade/Resource_GBK.h", "opencascade/Resource_LexicalCompare.hxx",
        "opencascade/Resource_Manager.hxx", "opencascade/Resource_NoSuchResource.hxx",
        "opencascade/Resource_Shiftjis.h", "opencascade/Resource_Unicode.hxx", "opencascade/Standard.hxx",
        "opencascade/Standard_AbortiveTransaction.hxx", "opencascade/Standard_Address.hxx",
        "opencascade/Standard_ArrayStreamBuffer.hxx", "opencascade/Standard_Assert.hxx",
        "opencascade/Standard_Atomic.hxx", "opencascade/Standard_Boolean.hxx", "opencascade/Standard_Byte.hxx",
        "opencascade/Standard_CLocaleSentry.hxx", "opencascade/Standard_CString.hxx",
        "opencascade/Standard_Character.hxx", "opencascade/Standard_Condition.hxx",
        "opencascade/Standard_ConstructionError.hxx", "opencascade/Standard_DimensionError.hxx",
        "opencascade/Standard_DimensionMismatch.hxx", "opencascade/Standard_DivideByZero.hxx",
        "opencascade/Standard_DomainError.hxx", "opencascade/Standard_Dump.hxx",
        "opencascade/Standard_ErrorHandler.hxx", "opencascade/Standard_ExtCharacter.hxx",
        "opencascade/Standard_ExtString.hxx", "opencascade/Standard_Failure.hxx", "opencascade/Standard_GUID.hxx",
        "opencascade/Standard_Handle.hxx", "opencascade/Standard_HandlerStatus.hxx", "opencascade/Standard_IStream.hxx",
        "opencascade/Standard_ImmutableObject.hxx", "opencascade/Standard_Integer.hxx",
        "opencascade/Standard_JmpBuf.hxx", "opencascade/Standard_LicenseError.hxx",
        "opencascade/Standard_LicenseNotFound.hxx", "opencascade/Standard_MMgrOpt.hxx",
        "opencascade/Standard_MMgrRaw.hxx", "opencascade/Standard_MMgrRoot.hxx",
        "opencascade/Standard_MMgrTBBalloc.hxx", "opencascade/Standard_Macro.hxx",
        "opencascade/Standard_MultiplyDefined.hxx", "opencascade/Standard_Mutex.hxx",
        "opencascade/Standard_NegativeValue.hxx", "opencascade/Standard_NoMoreObject.hxx",
        "opencascade/Standard_NoSuchObject.hxx", "opencascade/Standard_NotImplemented.hxx",
        "opencascade/Standard_NullObject.hxx", "opencascade/Standard_NullValue.hxx",
        "opencascade/Standard_NumericError.hxx", "opencascade/Standard_OStream.hxx",
        "opencascade/Standard_OutOfMemory.hxx", "opencascade/Standard_OutOfRange.hxx",
        "opencascade/Standard_Overflow.hxx", "opencascade/Standard_PByte.hxx", "opencascade/Standard_PCharacter.hxx",
        "opencascade/Standard_PErrorHandler.hxx", "opencascade/Standard_PExtCharacter.hxx",
        "opencascade/Standard_Persistent.hxx", "opencascade/Standard_PrimitiveTypes.hxx",
        "opencascade/Standard_ProgramError.hxx", "opencascade/Standard_RangeError.hxx",
        "opencascade/Standard_ReadBuffer.hxx", "opencascade/Standard_ReadLineBuffer.hxx",
        "opencascade/Standard_Real.hxx", "opencascade/Standard_SStream.hxx", "opencascade/Standard_ShortReal.hxx",
        "opencascade/Standard_Size.hxx", "opencascade/Standard_Std.hxx", "opencascade/Standard_Stream.hxx",
        "opencascade/Standard_ThreadId.hxx", "opencascade/Standard_Time.hxx", "opencascade/Standard_TooManyUsers.hxx",
        "opencascade/Standard_Transient.hxx", "opencascade/Standard_Type.hxx", "opencascade/Standard_TypeDef.hxx",
        "opencascade/Standard_TypeMismatch.hxx", "opencascade/Standard_UUID.hxx", "opencascade/Standard_Underflow.hxx",
        "opencascade/Standard_Version.hxx", "opencascade/Standard_WarningsDisable.hxx",
        "opencascade/Standard_WarningsRestore.hxx", "opencascade/Standard_math.hxx", "opencascade/Standard_values.h",
        "opencascade/StdFail_InfiniteSolutions.hxx", "opencascade/StdFail_NotDone.hxx",
        "opencascade/StdFail_Undefined.hxx", "opencascade/StdFail_UndefinedDerivative.hxx",
        "opencascade/StdFail_UndefinedValue.hxx", "opencascade/Storage.hxx", "opencascade/Storage_ArrayOfCallBack.hxx",
        "opencascade/Storage_ArrayOfSchema.hxx", "opencascade/Storage_BaseDriver.hxx",
        "opencascade/Storage_BaseDriver.lxx", "opencascade/Storage_BucketOfPersistent.hxx",
        "opencascade/Storage_CallBack.hxx", "opencascade/Storage_Data.hxx",
        "opencascade/Storage_DataMapIteratorOfMapOfCallBack.hxx", "opencascade/Storage_DataMapIteratorOfMapOfPers.hxx",
        "opencascade/Storage_DefaultCallBack.hxx", "opencascade/Storage_Error.hxx",
        "opencascade/Storage_HArrayOfCallBack.hxx", "opencascade/Storage_HArrayOfSchema.hxx",
        "opencascade/Storage_HPArray.hxx", "opencascade/Storage_HSeqOfRoot.hxx", "opencascade/Storage_HeaderData.hxx",
        "opencascade/Storage_InternalData.hxx", "opencascade/Storage_Macros.hxx",
        "opencascade/Storage_MapOfCallBack.hxx", "opencascade/Storage_MapOfPers.hxx",
        "opencascade/Storage_OpenMode.hxx", "opencascade/Storage_PArray.hxx", "opencascade/Storage_PType.hxx",
        "opencascade/Storage_Position.hxx", "opencascade/Storage_Root.hxx", "opencascade/Storage_RootData.hxx",
        "opencascade/Storage_Schema.hxx", "opencascade/Storage_Schema.lxx", "opencascade/Storage_SeqOfRoot.hxx",
        "opencascade/Storage_SolveMode.hxx", "opencascade/Storage_StreamExtCharParityError.hxx",
        "opencascade/Storage_StreamFormatError.hxx", "opencascade/Storage_StreamModeError.hxx",
        "opencascade/Storage_StreamReadError.hxx", "opencascade/Storage_StreamTypeMismatchError.hxx",
        "opencascade/Storage_StreamUnknownTypeError.hxx", "opencascade/Storage_StreamWriteError.hxx",
        "opencascade/Storage_TypeData.hxx", "opencascade/Storage_TypedCallBack.hxx",
        "opencascade/TColStd_Array1OfAsciiString.hxx", "opencascade/TColStd_Array1OfBoolean.hxx",
        "opencascade/TColStd_Array1OfByte.hxx", "opencascade/TColStd_Array1OfCharacter.hxx",
        "opencascade/TColStd_Array1OfExtendedString.hxx", "opencascade/TColStd_Array1OfInteger.hxx",
        "opencascade/TColStd_Array1OfListOfInteger.hxx", "opencascade/TColStd_Array1OfReal.hxx",
        "opencascade/TColStd_Array1OfTransient.hxx", "opencascade/TColStd_Array2OfBoolean.hxx",
        "opencascade/TColStd_Array2OfCharacter.hxx", "opencascade/TColStd_Array2OfInteger.hxx",
        "opencascade/TColStd_Array2OfReal.hxx", "opencascade/TColStd_Array2OfTransient.hxx",
        "opencascade/TColStd_DataMapIteratorOfDataMapOfAsciiStringInteger.hxx",
        "opencascade/TColStd_DataMapIteratorOfDataMapOfIntegerInteger.hxx",
        "opencascade/TColStd_DataMapIteratorOfDataMapOfIntegerListOfInteger.hxx",
        "opencascade/TColStd_DataMapIteratorOfDataMapOfIntegerReal.hxx",
        "opencascade/TColStd_DataMapIteratorOfDataMapOfIntegerTransient.hxx",
        "opencascade/TColStd_DataMapIteratorOfDataMapOfStringInteger.hxx",
        "opencascade/TColStd_DataMapIteratorOfDataMapOfTransientTransient.hxx",
        "opencascade/TColStd_DataMapOfAsciiStringInteger.hxx", "opencascade/TColStd_DataMapOfIntegerInteger.hxx",
        "opencascade/TColStd_DataMapOfIntegerListOfInteger.hxx", "opencascade/TColStd_DataMapOfIntegerReal.hxx",
        "opencascade/TColStd_DataMapOfIntegerTransient.hxx", "opencascade/TColStd_DataMapOfStringInteger.hxx",
        "opencascade/TColStd_DataMapOfTransientTransient.hxx", "opencascade/TColStd_HArray1OfAsciiString.hxx",
        "opencascade/TColStd_HArray1OfBoolean.hxx", "opencascade/TColStd_HArray1OfByte.hxx",
        "opencascade/TColStd_HArray1OfCharacter.hxx", "opencascade/TColStd_HArray1OfExtendedString.hxx",
        "opencascade/TColStd_HArray1OfInteger.hxx", "opencascade/TColStd_HArray1OfListOfInteger.hxx",
        "opencascade/TColStd_HArray1OfReal.hxx", "opencascade/TColStd_HArray1OfTransient.hxx",
        "opencascade/TColStd_HArray2OfBoolean.hxx", "opencascade/TColStd_HArray2OfCharacter.hxx",
        "opencascade/TColStd_HArray2OfInteger.hxx", "opencascade/TColStd_HArray2OfReal.hxx",
        "opencascade/TColStd_HArray2OfTransient.hxx", "opencascade/TColStd_HPackedMapOfInteger.hxx",
        "opencascade/TColStd_HPackedMapOfInteger.lxx", "opencascade/TColStd_HSequenceOfAsciiString.hxx",
        "opencascade/TColStd_HSequenceOfExtendedString.hxx", "opencascade/TColStd_HSequenceOfHAsciiString.hxx",
        "opencascade/TColStd_HSequenceOfHExtendedString.hxx", "opencascade/TColStd_HSequenceOfInteger.hxx",
        "opencascade/TColStd_HSequenceOfReal.hxx", "opencascade/TColStd_HSequenceOfTransient.hxx",
        "opencascade/TColStd_IndexedDataMapOfStringString.hxx",
        "opencascade/TColStd_IndexedDataMapOfTransientTransient.hxx", "opencascade/TColStd_IndexedMapOfInteger.hxx",
        "opencascade/TColStd_IndexedMapOfReal.hxx", "opencascade/TColStd_IndexedMapOfTransient.hxx",
        "opencascade/TColStd_ListIteratorOfListOfAsciiString.hxx",
        "opencascade/TColStd_ListIteratorOfListOfInteger.hxx", "opencascade/TColStd_ListIteratorOfListOfReal.hxx",
        "opencascade/TColStd_ListIteratorOfListOfTransient.hxx", "opencascade/TColStd_ListOfAsciiString.hxx",
        "opencascade/TColStd_ListOfInteger.hxx", "opencascade/TColStd_ListOfReal.hxx",
        "opencascade/TColStd_ListOfTransient.hxx", "opencascade/TColStd_MapIntegerHasher.hxx",
        "opencascade/TColStd_MapIteratorOfMapOfAsciiString.hxx", "opencascade/TColStd_MapIteratorOfMapOfInteger.hxx",
        "opencascade/TColStd_MapIteratorOfMapOfReal.hxx", "opencascade/TColStd_MapIteratorOfMapOfTransient.hxx",
        "opencascade/TColStd_MapIteratorOfPackedMapOfInteger.hxx", "opencascade/TColStd_MapOfAsciiString.hxx",
        "opencascade/TColStd_MapOfInteger.hxx", "opencascade/TColStd_MapOfReal.hxx",
        "opencascade/TColStd_MapOfTransient.hxx", "opencascade/TColStd_MapRealHasher.hxx",
        "opencascade/TColStd_MapTransientHasher.hxx", "opencascade/TColStd_PackedMapOfInteger.hxx",
        "opencascade/TColStd_SequenceOfAddress.hxx", "opencascade/TColStd_SequenceOfAsciiString.hxx",
        "opencascade/TColStd_SequenceOfBoolean.hxx", "opencascade/TColStd_SequenceOfExtendedString.hxx",
        "opencascade/TColStd_SequenceOfHAsciiString.hxx", "opencascade/TColStd_SequenceOfHExtendedString.hxx",
        "opencascade/TColStd_SequenceOfInteger.hxx", "opencascade/TColStd_SequenceOfReal.hxx",
        "opencascade/TColStd_SequenceOfTransient.hxx", "opencascade/TColgp_Array1OfCirc2d.hxx",
        "opencascade/TColgp_Array1OfDir.hxx", "opencascade/TColgp_Array1OfDir2d.hxx",
        "opencascade/TColgp_Array1OfLin2d.hxx", "opencascade/TColgp_Array1OfPnt.hxx",
        "opencascade/TColgp_Array1OfPnt2d.hxx", "opencascade/TColgp_Array1OfVec.hxx",
        "opencascade/TColgp_Array1OfVec2d.hxx", "opencascade/TColgp_Array1OfXY.hxx",
        "opencascade/TColgp_Array1OfXYZ.hxx", "opencascade/TColgp_Array2OfCirc2d.hxx",
        "opencascade/TColgp_Array2OfDir.hxx", "opencascade/TColgp_Array2OfDir2d.hxx",
        "opencascade/TColgp_Array2OfLin2d.hxx", "opencascade/TColgp_Array2OfPnt.hxx",
        "opencascade/TColgp_Array2OfPnt2d.hxx", "opencascade/TColgp_Array2OfVec.hxx",
        "opencascade/TColgp_Array2OfVec2d.hxx", "opencascade/TColgp_Array2OfXY.hxx",
        "opencascade/TColgp_Array2OfXYZ.hxx", "opencascade/TColgp_HArray1OfCirc2d.hxx",
        "opencascade/TColgp_HArray1OfDir.hxx", "opencascade/TColgp_HArray1OfDir2d.hxx",
        "opencascade/TColgp_HArray1OfLin2d.hxx", "opencascade/TColgp_HArray1OfPnt.hxx",
        "opencascade/TColgp_HArray1OfPnt2d.hxx", "opencascade/TColgp_HArray1OfVec.hxx",
        "opencascade/TColgp_HArray1OfVec2d.hxx", "opencascade/TColgp_HArray1OfXY.hxx",
        "opencascade/TColgp_HArray1OfXYZ.hxx", "opencascade/TColgp_HArray2OfCirc2d.hxx",
        "opencascade/TColgp_HArray2OfDir.hxx", "opencascade/TColgp_HArray2OfDir2d.hxx",
        "opencascade/TColgp_HArray2OfLin2d.hxx", "opencascade/TColgp_HArray2OfPnt.hxx",
        "opencascade/TColgp_HArray2OfPnt2d.hxx", "opencascade/TColgp_HArray2OfVec.hxx",
        "opencascade/TColgp_HArray2OfVec2d.hxx", "opencascade/TColgp_HArray2OfXY.hxx",
        "opencascade/TColgp_HArray2OfXYZ.hxx", "opencascade/TColgp_HSequenceOfDir.hxx",
        "opencascade/TColgp_HSequenceOfDir2d.hxx", "opencascade/TColgp_HSequenceOfPnt.hxx",
        "opencascade/TColgp_HSequenceOfPnt2d.hxx", "opencascade/TColgp_HSequenceOfVec.hxx",
        "opencascade/TColgp_HSequenceOfVec2d.hxx", "opencascade/TColgp_HSequenceOfXY.hxx",
        "opencascade/TColgp_HSequenceOfXYZ.hxx", "opencascade/TColgp_SequenceOfArray1OfPnt2d.hxx",
        "opencascade/TColgp_SequenceOfAx1.hxx", "opencascade/TColgp_SequenceOfDir.hxx",
        "opencascade/TColgp_SequenceOfDir2d.hxx", "opencascade/TColgp_SequenceOfPnt.hxx",
        "opencascade/TColgp_SequenceOfPnt2d.hxx", "opencascade/TColgp_SequenceOfVec.hxx",
        "opencascade/TColgp_SequenceOfVec2d.hxx", "opencascade/TColgp_SequenceOfXY.hxx",
        "opencascade/TColgp_SequenceOfXYZ.hxx", "opencascade/TCollection.hxx", "opencascade/TCollection_Array1.gxx",
        "opencascade/TCollection_Array1.lxx", "opencascade/TCollection_Array2.gxx",
        "opencascade/TCollection_Array2.lxx", "opencascade/TCollection_AsciiString.hxx",
        "opencascade/TCollection_AsciiString.lxx", "opencascade/TCollection_BaseSequence.hxx",
        "opencascade/TCollection_BaseSequence.lxx", "opencascade/TCollection_BasicMap.hxx",
        "opencascade/TCollection_BasicMap.lxx", "opencascade/TCollection_BasicMapIterator.hxx",
        "opencascade/TCollection_BasicMapIterator.lxx", "opencascade/TCollection_DataMap.gxx",
        "opencascade/TCollection_DataMapIterator.gxx", "opencascade/TCollection_DataMapNode.gxx",
        "opencascade/TCollection_DataMapNode.lxx", "opencascade/TCollection_DoubleMap.gxx",
        "opencascade/TCollection_DoubleMapIterator.gxx", "opencascade/TCollection_DoubleMapNode.gxx",
        "opencascade/TCollection_DoubleMapNode.lxx", "opencascade/TCollection_ExtendedString.hxx",
        "opencascade/TCollection_HArray1.gxx", "opencascade/TCollection_HArray1.lxx",
        "opencascade/TCollection_HArray2.gxx", "opencascade/TCollection_HArray2.lxx",
        "opencascade/TCollection_HAsciiString.hxx", "opencascade/TCollection_HAsciiString.lxx",
        "opencascade/TCollection_HExtendedString.hxx", "opencascade/TCollection_HSequence.gxx",
        "opencascade/TCollection_HSequence.lxx", "opencascade/TCollection_IndexedDataMap.gxx",
        "opencascade/TCollection_IndexedDataMapNode.gxx", "opencascade/TCollection_IndexedDataMapNode.lxx",
        "opencascade/TCollection_IndexedMap.gxx", "opencascade/TCollection_IndexedMapNode.gxx",
        "opencascade/TCollection_IndexedMapNode.lxx", "opencascade/TCollection_List.gxx",
        "opencascade/TCollection_List.lxx", "opencascade/TCollection_ListIterator.gxx",
        "opencascade/TCollection_ListIterator.lxx", "opencascade/TCollection_ListNode.gxx",
        "opencascade/TCollection_ListNode.lxx", "opencascade/TCollection_Map.gxx",
        "opencascade/TCollection_MapHasher.gxx", "opencascade/TCollection_MapIterator.gxx",
        "opencascade/TCollection_MapNode.hxx", "opencascade/TCollection_MapNode.lxx",
        "opencascade/TCollection_MapNodePtr.hxx", "opencascade/TCollection_SeqNode.hxx",
        "opencascade/TCollection_SeqNode.lxx", "opencascade/TCollection_SeqNodePtr.hxx",
        "opencascade/TCollection_Sequence.gxx", "opencascade/TCollection_Sequence.lxx",
        "opencascade/TCollection_SequenceNode.gxx", "opencascade/TCollection_SequenceNode.lxx",
        "opencascade/TCollection_Side.hxx", "opencascade/TCollection_StdMapNode.gxx",
        "opencascade/TCollection_StdMapNode.lxx", "opencascade/TShort_Array1OfShortReal.hxx",
        "opencascade/TShort_Array2OfShortReal.hxx", "opencascade/TShort_HArray1OfShortReal.hxx",
        "opencascade/TShort_HArray2OfShortReal.hxx", "opencascade/TShort_HSequenceOfShortReal.hxx",
        "opencascade/TShort_SequenceOfShortReal.hxx", "opencascade/TopLoc_Datum3D.hxx",
        "opencascade/TopLoc_Datum3D.lxx", "opencascade/TopLoc_IndexedMapOfLocation.hxx",
        "opencascade/TopLoc_ItemLocation.hxx", "opencascade/TopLoc_Location.hxx", "opencascade/TopLoc_Location.lxx",
        "opencascade/TopLoc_MapIteratorOfMapOfLocation.hxx", "opencascade/TopLoc_MapLocationHasher.hxx",
        "opencascade/TopLoc_MapOfLocation.hxx", "opencascade/TopLoc_SListNodeOfItemLocation.hxx",
        "opencascade/TopLoc_SListNodeOfItemLocation.lxx", "opencascade/TopLoc_SListOfItemLocation.hxx",
        "opencascade/Units.hxx", "opencascade/UnitsAPI.hxx", "opencascade/UnitsAPI_SystemUnits.hxx",
        "opencascade/Units_Dimensions.hxx", "opencascade/Units_Dimensions.lxx", "opencascade/Units_Explorer.hxx",
        "opencascade/Units_Lexicon.hxx", "opencascade/Units_Lexicon.lxx", "opencascade/Units_MathSentence.hxx",
        "opencascade/Units_Measurement.hxx", "opencascade/Units_NoSuchType.hxx", "opencascade/Units_NoSuchUnit.hxx",
        "opencascade/Units_Operators.hxx", "opencascade/Units_QtsSequence.hxx",
        "opencascade/Units_QuantitiesSequence.hxx", "opencascade/Units_Quantity.hxx", "opencascade/Units_Quantity.lxx",
        "opencascade/Units_Sentence.hxx", "opencascade/Units_Sentence.lxx", "opencascade/Units_ShiftedToken.hxx",
        "opencascade/Units_ShiftedUnit.hxx", "opencascade/Units_TksSequence.hxx", "opencascade/Units_Token.hxx",
        "opencascade/Units_Token.lxx", "opencascade/Units_TokensSequence.hxx", "opencascade/Units_Unit.hxx",
        "opencascade/Units_Unit.lxx", "opencascade/Units_UnitSentence.hxx", "opencascade/Units_UnitsDictionary.hxx",
        "opencascade/Units_UnitsDictionary.lxx", "opencascade/Units_UnitsLexicon.hxx",
        "opencascade/Units_UnitsLexicon.lxx", "opencascade/Units_UnitsSequence.hxx",
        "opencascade/Units_UnitsSystem.hxx", "opencascade/Units_UtsSequence.hxx", "opencascade/gp.hxx",
        "opencascade/gp.lxx", "opencascade/gp_Ax1.hxx", "opencascade/gp_Ax1.lxx", "opencascade/gp_Ax2.hxx",
        "opencascade/gp_Ax2.lxx", "opencascade/gp_Ax22d.hxx", "opencascade/gp_Ax22d.lxx", "opencascade/gp_Ax2d.hxx",
        "opencascade/gp_Ax2d.lxx", "opencascade/gp_Ax3.hxx", "opencascade/gp_Ax3.lxx", "opencascade/gp_Circ.hxx",
        "opencascade/gp_Circ.lxx", "opencascade/gp_Circ2d.hxx", "opencascade/gp_Circ2d.lxx", "opencascade/gp_Cone.hxx",
        "opencascade/gp_Cone.lxx", "opencascade/gp_Cylinder.hxx", "opencascade/gp_Cylinder.lxx",
        "opencascade/gp_Dir.hxx", "opencascade/gp_Dir.lxx", "opencascade/gp_Dir2d.hxx", "opencascade/gp_Dir2d.lxx",
        "opencascade/gp_Elips.hxx", "opencascade/gp_Elips.lxx", "opencascade/gp_Elips2d.hxx",
        "opencascade/gp_Elips2d.lxx", "opencascade/gp_EulerSequence.hxx", "opencascade/gp_GTrsf.hxx",
        "opencascade/gp_GTrsf.lxx", "opencascade/gp_GTrsf2d.hxx", "opencascade/gp_GTrsf2d.lxx",
        "opencascade/gp_Hypr.hxx", "opencascade/gp_Hypr.lxx", "opencascade/gp_Hypr2d.hxx", "opencascade/gp_Hypr2d.lxx",
        "opencascade/gp_Lin.hxx", "opencascade/gp_Lin.lxx", "opencascade/gp_Lin2d.hxx", "opencascade/gp_Lin2d.lxx",
        "opencascade/gp_Mat.hxx", "opencascade/gp_Mat.lxx", "opencascade/gp_Mat2d.hxx", "opencascade/gp_Mat2d.lxx",
        "opencascade/gp_Parab.hxx", "opencascade/gp_Parab.lxx", "opencascade/gp_Parab2d.hxx",
        "opencascade/gp_Parab2d.lxx", "opencascade/gp_Pln.hxx", "opencascade/gp_Pln.lxx", "opencascade/gp_Pnt.hxx",
        "opencascade/gp_Pnt.lxx", "opencascade/gp_Pnt2d.hxx", "opencascade/gp_Pnt2d.lxx",
        "opencascade/gp_Quaternion.hxx", "opencascade/gp_Quaternion.lxx", "opencascade/gp_QuaternionNLerp.hxx",
        "opencascade/gp_QuaternionSLerp.hxx", "opencascade/gp_Sphere.hxx", "opencascade/gp_Sphere.lxx",
        "opencascade/gp_Torus.hxx", "opencascade/gp_Torus.lxx", "opencascade/gp_Trsf.hxx", "opencascade/gp_Trsf.lxx",
        "opencascade/gp_Trsf2d.hxx", "opencascade/gp_Trsf2d.lxx", "opencascade/gp_TrsfForm.hxx",
        "opencascade/gp_TrsfNLerp.hxx", "opencascade/gp_Vec.hxx", "opencascade/gp_Vec.lxx", "opencascade/gp_Vec2d.hxx",
        "opencascade/gp_Vec2d.lxx", "opencascade/gp_VectorWithNullMagnitude.hxx", "opencascade/gp_XY.hxx",
        "opencascade/gp_XY.lxx", "opencascade/gp_XYZ.hxx", "opencascade/gp_XYZ.lxx", "opencascade/math.hxx",
        "opencascade/math_Array1OfValueAndWeight.hxx", "opencascade/math_BFGS.hxx", "opencascade/math_BFGS.lxx",
        "opencascade/math_BissecNewton.hxx", "opencascade/math_BissecNewton.lxx", "opencascade/math_BracketMinimum.hxx",
        "opencascade/math_BracketMinimum.lxx", "opencascade/math_BracketedRoot.hxx",
        "opencascade/math_BracketedRoot.lxx", "opencascade/math_BrentMinimum.hxx", "opencascade/math_BrentMinimum.lxx",
        "opencascade/math_BullardGenerator.hxx", "opencascade/math_ComputeGaussPointsAndWeights.hxx",
        "opencascade/math_ComputeKronrodPointsAndWeights.hxx", "opencascade/math_Crout.hxx",
        "opencascade/math_Crout.lxx", "opencascade/math_DirectPolynomialRoots.hxx",
        "opencascade/math_DirectPolynomialRoots.lxx", "opencascade/math_DoubleTab.hxx",
        "opencascade/math_DoubleTab.lxx", "opencascade/math_EigenValuesSearcher.hxx", "opencascade/math_FRPR.hxx",
        "opencascade/math_FRPR.lxx", "opencascade/math_Function.hxx", "opencascade/math_FunctionAllRoots.hxx",
        "opencascade/math_FunctionAllRoots.lxx", "opencascade/math_FunctionRoot.hxx",
        "opencascade/math_FunctionRoot.lxx", "opencascade/math_FunctionRoots.hxx", "opencascade/math_FunctionRoots.lxx",
        "opencascade/math_FunctionSample.hxx", "opencascade/math_FunctionSet.hxx",
        "opencascade/math_FunctionSetRoot.hxx", "opencascade/math_FunctionSetRoot.lxx",
        "opencascade/math_FunctionSetWithDerivatives.hxx", "opencascade/math_FunctionWithDerivative.hxx",
        "opencascade/math_Gauss.hxx", "opencascade/math_GaussLeastSquare.hxx", "opencascade/math_GaussLeastSquare.lxx",
        "opencascade/math_GaussMultipleIntegration.hxx", "opencascade/math_GaussMultipleIntegration.lxx",
        "opencascade/math_GaussPoints.hxx", "opencascade/math_GaussSetIntegration.hxx",
        "opencascade/math_GaussSetIntegration.lxx", "opencascade/math_GaussSingleIntegration.hxx",
        "opencascade/math_GaussSingleIntegration.lxx", "opencascade/math_GlobOptMin.hxx",
        "opencascade/math_Householder.hxx", "opencascade/math_Householder.lxx", "opencascade/math_IntegerVector.hxx",
        "opencascade/math_Jacobi.hxx", "opencascade/math_Jacobi.lxx", "opencascade/math_KronrodSingleIntegration.hxx",
        "opencascade/math_KronrodSingleIntegration.lxx", "opencascade/math_Matrix.hxx", "opencascade/math_Matrix.lxx",
        "opencascade/math_MultipleVarFunction.hxx", "opencascade/math_MultipleVarFunctionWithGradient.hxx",
        "opencascade/math_MultipleVarFunctionWithHessian.hxx", "opencascade/math_NewtonFunctionRoot.hxx",
        "opencascade/math_NewtonFunctionRoot.lxx", "opencascade/math_NewtonFunctionSetRoot.hxx",
        "opencascade/math_NewtonFunctionSetRoot.lxx", "opencascade/math_NewtonMinimum.hxx",
        "opencascade/math_NewtonMinimum.lxx", "opencascade/math_NotSquare.hxx", "opencascade/math_PSO.hxx",
        "opencascade/math_PSOParticlesPool.hxx", "opencascade/math_Powell.hxx", "opencascade/math_Powell.lxx",
        "opencascade/math_Recipes.hxx", "opencascade/math_SVD.hxx", "opencascade/math_SVD.lxx",
        "opencascade/math_SingularMatrix.hxx", "opencascade/math_Status.hxx",
        "opencascade/math_TrigonometricEquationFunction.hxx", "opencascade/math_TrigonometricFunctionRoots.hxx",
        "opencascade/math_TrigonometricFunctionRoots.lxx", "opencascade/math_Uzawa.hxx", "opencascade/math_Uzawa.lxx",
        "opencascade/math_ValueAndWeight.hxx",
        "opencascade/math_Vector.hxx" }), }, target = "org.bytedeco.opencascade", global = "org.bytedeco.opencascade.global.opencascade")

public class Foundation implements InfoMapper {
    static {
        Loader.checkVersion("org.bytedeco", "opencascade");
    }

    public void map(InfoMap infoMap) {
        infoMap.put(new Info("DEFINE_STANDARD_ALLOC", "DEFINE_STANDARD_ALLOC_ARRAY", "DEFINE_STANDARD_ALLOC_PLACEMENT",
                "DEFINE_NCOLLECTION_ALLOC", "STANDARD_ALIGNED", "WORKAROUND_SUNPRO_NEW_PLACEMENT", "Standard_EXPORT")
                        .cppTypes().annotations());
        infoMap.put(new Info("__QNX__").define(false));
        infoMap.put(new Info("defined (__alpha) || defined(DECOSF1)").define(false));
        infoMap.put(new Info("NCollection_Haft").skip());
    }
}
